language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-x86-android-29
